-- Catálogo semilla: 29 vinos españoles investigados manualmente (Rioja, Ribera del Duero, Priorat).
-- Precios estimados propios a partir de fuentes públicas citadas en data_sources; no son datos scrapeados
-- de Wine-Searcher/Liv-ex/Vivino. Ver confidence_rationale por fila para el criterio de cada nivel de confianza.

insert into public.reference_wines
  (name, winery, region, subregion, color, vintage, grape_varieties,
   estimated_market_price_eur, price_range_low_eur, price_range_high_eur,
   confidence_level, confidence_rationale, data_sources, price_as_of_date, external_search_url)
values
  ('Imperial Gran Reserva', 'CVNE (Compañía Vinícola del Norte de España)', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2018, ARRAY['Tempranillo', 'Graciano', 'Mazuelo'], 72, 55, 95, 'medio'::confidence_level, 'Precio agregado consistente entre Wine-Searcher (promedio ~109 USD) y tienda oficial CVNE, pero sin evidencia de reventa en mercado secundario español.', ARRAY['Wine-Searcher (precio medio agregado)', 'CVNE tienda oficial'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/c+v+n+e+imperiale+grand+rsrv+doca+rioja+alta+spain'),
  ('Gran Reserva 904', 'La Rioja Alta, S.A.', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2015, ARRAY['Tempranillo', 'Graciano'], 90, 75, 110, 'medio'::confidence_level, 'Varios retailers (Enbotella, Total Wine, Binny''s) coinciden en el rango; añadas antiguas (2000) muestran cierta revalorización, pero sin comps de subasta verificados.', ARRAY['Enbotella (retail España)', 'Wine-Searcher (promedio EE.UU.)', 'Total Wine & More'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/la+s+a+grand+rsrv+904+doca+rioja+alta+spain'),
  ('Gran Reserva 890 (Selección Especial)', 'La Rioja Alta, S.A.', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2010, ARRAY['Tempranillo', 'Graciano', 'Mazuelo'], 270, 230, 400, 'medio'::confidence_level, 'Producción muy limitada con precios altos y consistentes en varios retailers de EE.UU. (Skurnik, Saratoga Wine), pero sin comps de subasta específicos en España.', ARRAY['Skurnik Wines & Spirits', 'Wine-Searcher (promedio)', 'Saratoga Wine'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/la+s+a+grand+rsrv+890+doca+rioja+alta+spain'),
  ('Castillo Ygay Tinto Gran Reserva Especial', 'Marqués de Murrieta', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2012, ARRAY['Tempranillo', 'Mazuelo', 'Graciano'], 290, 250, 330, 'medio'::confidence_level, 'Precio mínimo oficial de bodega (€290, caja de madera) coincide con retailers internacionales (vinello.eu ~€287), pero no hay evidencia de mercado de reventa activo comparable al de Vega Sicilia.', ARRAY['marquesdemurrieta.com (precio oficial bodega)', 'vinello.eu', 'Total Wine & More'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/marquis+de+murrieta+castillo+y+gay+grand+rsrv+spc+doca+rioja+alta+spain'),
  ('Remírez de Ganuza Reserva', 'Bodegas Remírez de Ganuza', 'rioja'::wine_region, 'Rioja Alavesa', 'tinto'::wine_color, 2018, ARRAY['Tempranillo', 'Graciano', 'Garnacha'], 62, 55, 72, 'medio'::confidence_level, 'Precio retail muy consistente entre seis tiendas españolas distintas (Bodeboca, Drinks&Co, TomeVinos, Enbotella), pero sin evidencia de reventa.', ARRAY['Bodeboca', 'Drinks&Co', 'TomeVinos'], '2026-07-27'::date, 'https://www.bodeboca.com/vino/remirez-ganuza-reserva-2017'),
  ('Contador', 'Bodega Contador (Benjamín Romeo)', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2019, ARRAY['Tempranillo'], 200, 150, 300, 'bajo'::confidence_level, 'El único dato de precio concreto encontrado es una añada envejecida (2005) a 1.699,90 € en Vinissimus (precio de coleccionista, no representativo de añada actual); sin datos de precio ni evidencia de mercado secundario para añadas recientes, la estimación aplica una prima al segmento de precio de otros vinos de la bodega (Alma de Contador ~€120).', ARRAY['Vinissimus (listado Contador 2005)', 'Bodeboca (colección Benjamín Romeo)'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/contador/'),
  ('Viñas de Gain', 'Artadi', 'rioja'::wine_region, 'Rioja Alavesa', 'tinto'::wine_color, 2022, ARRAY['Tempranillo'], 29, 26, 33, 'medio'::confidence_level, 'Precio muy uniforme entre cinco retailers distintos (Bodeboca, El Corte Inglés, La Vinatería), típico de un vino de entrada de bodega icónica sin mercado de reventa propio.', ARRAY['Bodeboca', 'El Corte Inglés / Club del Gourmet', 'Vinissimus'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/vinas-de-gain/'),
  ('Viña El Pisón', 'Artadi', 'rioja'::wine_region, 'Rioja Alavesa', 'tinto'::wine_color, 2023, ARRAY['Tempranillo'], 340, 300, 380, 'medio'::confidence_level, 'Vino de parcela única de culto (viñedo de 1945) con fuente de precio fuerte (Vinissimus, €341,30), pero sin comps adicionales de mercado secundario o subasta verificados.', ARRAY['Vinissimus', 'Lafuente.es', 'Decántalo'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/artadi-vina-el-pison/'),
  ('Prado Enea Gran Reserva', 'Bodegas Muga', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2019, ARRAY['Tempranillo', 'Garnacha', 'Graciano', 'Mazuelo'], 78, 70, 100, 'medio'::confidence_level, 'Precio consistente entre Bodeboca y Wine Palace (~€76), con precio algo superior en mercado estadounidense; sin evidencia de reventa española.', ARRAY['Bodeboca', 'Wine Palace', 'Wine-Searcher (promedio EE.UU.)'], '2026-07-27'::date, 'https://www.bodeboca.com/vino/muga-prado-enea-gran-reserva-2019'),
  ('Roda I Reserva', 'Bodegas Roda', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2019, ARRAY['Tempranillo', 'Graciano'], 46, 40, 54, 'medio'::confidence_level, 'Rango de precio consistente entre varios retailers españoles (Mariano Madrueño, Enbotella, Birdievinos), típico de retail activo sin mercado secundario.', ARRAY['Enbotella', 'Mariano Madrueño', 'TomeVinos'], '2026-07-27'::date, 'https://www.enbotella.com/es/bodegas-roda-i-reserva'),
  ('Viña Tondonia Reserva', 'R. López de Heredia', 'rioja'::wine_region, 'Rioja Alta', 'tinto'::wine_color, 2012, ARRAY['Tempranillo', 'Garnacho', 'Mazuelo', 'Graciano'], 65, 55, 75, 'medio'::confidence_level, 'Precio medio agregado de Wine-Searcher (~67 USD) consistente con retailers estadounidenses; bodega tradicionalista con culto entre coleccionistas pero sin comps de reventa claros.', ARRAY['Wine-Searcher (promedio EE.UU.)', 'Woodland Hills Wine Company', 'Marketview Liquor'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/r+lopez+de+heredia+vina+tondonia+rsrv+doca+rioja+alta+spain/1/usa'),
  ('Barón de Chirel Reserva', 'Marqués de Riscal', 'rioja'::wine_region, 'Rioja Alavesa', 'tinto'::wine_color, 2020, ARRAY['Tempranillo', 'Cabernet Sauvignon'], 108, 100, 120, 'medio'::confidence_level, 'Precio consistente entre Lavinia, Enbotella y tienda oficial de la bodega; retail activo sin evidencia de reventa.', ARRAY['Lavinia', 'Enbotella', 'tienda.marquesderiscal.com'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/marquis+de+riscal+baron+chirel+rsrv+doca+rioja+alavesa+spain'),
  ('Único', 'Vega Sicilia', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2013, ARRAY['Tempranillo', 'Cabernet Sauvignon'], 480, 396, 565, 'alto'::confidence_level, 'Precios consistentes en múltiples retailers españoles (Idealo, Bodeboca) y, según investigación previa, es uno de los dos únicos vinos españoles (junto a Pingus) con demanda de inversión estable reconocida por brokers de vino como Vin-X.', ARRAY['Idealo (comparador de precios España)', 'Bodeboca', 'Vin-X (broker de inversión en vino, investigación previa)'], '2026-07-27'::date, 'https://www.idealo.es/precios/200936649/vega-sicilia-unico.html'),
  ('Valbuena 5º Año', 'Vega Sicilia', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2020, ARRAY['Tempranillo', 'Merlot'], 180, 145, 199, 'alto'::confidence_level, 'Segunda etiqueta de Vega Sicilia con precio muy consistente en múltiples retailers españoles (Idealo, Bodeboca, TomeVinos) y mercado muy líquido, aunque sin comps de subasta tan documentados como Único.', ARRAY['Idealo (comparador de precios España)', 'Bodeboca', 'TomeVinos'], '2026-07-27'::date, 'https://www.idealo.es/precios/200486630/vega-sicilia-valbuena-5.html'),
  ('Pingus', 'Dominio de Pingus', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2019, ARRAY['Tempranillo'], 700, 500, 1000, 'alto'::confidence_level, 'Según investigación previa, es el vino español más negociado en mercado secundario, junto con Vega Sicilia el único con demanda de inversión estable; fuentes adicionales confirman rango de 300-1.000€ dependiendo de añada.', ARRAY['Investigación previa (anchor, brokers tipo Vin-X)', 'redroo.es (análisis de precio Pingus)', 'Wikipedia — Dominio de Pingus'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/pingus+ribera+duero+castilla+y+leon+spain'),
  ('Flor de Pingus', 'Dominio de Pingus', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2022, ARRAY['Tempranillo'], 150, 130, 190, 'medio'::confidence_level, 'Segunda marca de Pingus con precio consistente en varios retailers (Vinissimus, Bodeboca, Vinatis); se beneficia de la reputación de la bodega pero no hay evidencia de reventa propia documentada.', ARRAY['Vinissimus', 'Bodeboca', 'Vinatis.es'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/flor-de-pingus/'),
  ('Aalto', 'Bodegas Aalto', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2023, ARRAY['Tempranillo'], 40, 29, 47, 'medio'::confidence_level, 'Precio retail consistente en varias tiendas españolas (Bodeboca, TomeVinos, Vinissimus); sin evidencia de reventa.', ARRAY['Bodeboca', 'Vinissimus', 'TomeVinos'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/aalto/'),
  ('Aalto PS', 'Bodegas Aalto', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2023, ARRAY['Tempranillo'], 83, 75, 95, 'medio'::confidence_level, 'Cuvée superior de Aalto de parcelas seleccionadas; precio de Vinissimus (€82,85) es la referencia principal, sin comps adicionales de mercado secundario.', ARRAY['Vinissimus', 'Devinoavino.es', 'Ideavinos'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/aalto-ps/'),
  ('Tinto Pesquera Janus Gran Reserva', 'Bodegas Alejandro Fernández (Pesquera)', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 1994, ARRAY['Tempranillo'], 265, 239, 290, 'bajo'::confidence_level, 'Producción extremadamente limitada y esporádica (solo elaborado en 1982, 1986, 1991 y 1994); evidencia de precio proviene de tiendas internacionales de vino fino, sin comps de subasta recientes verificables en el mercado español.', ARRAY['Best of Wines (Janus Gran Reserva)', 'K&L Wine Merchants', 'iDealwine'], '2026-07-27'::date, 'https://bestofwines.com/wine/spain/ribera-del-duero/bodegas-alejandro-fernandez-pesquera/janus-gran-reserva/'),
  ('Mauro', 'Bodegas Mauro', 'ribera_del_duero'::wine_region, 'Tudela de Duero (Vino de la Tierra de Castilla y León, fuera de la DO Ribera del Duero)', 'tinto'::wine_color, 2023, ARRAY['Tempranillo', 'Cabernet Sauvignon', 'Syrah'], 42, 37, 52, 'medio'::confidence_level, 'Precio retail consistente en varios comparadores y tiendas (Idealo, Vinissimus); nota: técnicamente fuera de la DO Ribera del Duero, se incluye por relevancia y pertenencia al valle del Duero.', ARRAY['Idealo (comparador de precios España)', 'Vinissimus', 'Vinoseleccion.com'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/mauro/'),
  ('Pícaro del Águila', 'Dominio del Águila', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2023, ARRAY['Tempranillo', 'Garnacha', 'Bobal', 'Albillo'], 31, 29, 34, 'medio'::confidence_level, 'Precio consistente entre Bodeboca, Lavinia y Vino-Vi; vino de viñas viejas de bodega de culto reciente sin mercado secundario propio.', ARRAY['Bodeboca', 'Lavinia', 'Vino-Vi'], '2026-07-27'::date, 'https://www.bodeboca.com/vino/picaro-aguila-2023'),
  ('Alión', 'Bodegas y Viñedos Alión (Vega Sicilia)', 'ribera_del_duero'::wine_region, null, 'tinto'::wine_color, 2022, ARRAY['Tempranillo'], 97, 90, 98, 'medio'::confidence_level, 'Segunda bodega del grupo Vega Sicilia, con precio retail consistente (Bodeboca, TomeVinos), pero sin evidencia de mercado secundario propio como el de Único.', ARRAY['Bodeboca', 'TomeVinos', 'Vinissimus'], '2026-07-27'::date, 'https://www.bodeboca.com/vino/alion-2022'),
  ('L''Ermita', 'Álvaro Palacios', 'priorat'::wine_region, 'Gratallops', 'tinto'::wine_color, 2022, ARRAY['Garnacha', 'Cariñena'], 1500, 1250, 1650, 'alto'::confidence_level, 'Uno de los vinos españoles más cotizados internacionalmente; precios coincidentes en varias fuentes independientes (Idealo, Wine Palace) y anclado en investigación previa (~€1.649 retail reciente).', ARRAY['Idealo (comparador de precios España)', 'Wine Palace', 'investigación previa (anchor)'], '2026-07-27'::date, 'https://www.idealo.es/precios/200922719/alvaro-palacios-l-ermita.html'),
  ('Clos Erasmus', 'Clos i Terrasses (Daphne Glorian)', 'priorat'::wine_region, 'Gratallops', 'tinto'::wine_color, 2022, ARRAY['Garnacha', 'Cariñena', 'Syrah'], 330, 280, 400, 'alto'::confidence_level, 'Primer vino español en obtener 100 puntos Parker; según spanishwinelover.com es uno de los pocos vinos españoles que se revaloriza en mercado secundario, y el precio de retail reciente (Vinissimus, €335) coincide con la investigación previa.', ARRAY['Vinissimus', 'artículo spanishwinelover.com sobre mercado secundario', 'investigación previa (anchor)'], '2026-07-27'::date, 'https://www.vinissimus.com/es/vino/clos-erasmus/'),
  ('Clos Mogador', 'Clos Mogador (René Barbier)', 'priorat'::wine_region, 'Gratallops', 'tinto'::wine_color, 2022, ARRAY['Garnacha', 'Cariñena', 'Syrah', 'Cabernet Sauvignon'], 105, 95, 120, 'medio'::confidence_level, 'Uno de los productores fundacionales del Priorat moderno; precio medio agregado de Wine-Searcher (~114 USD) consistente con retail internacional, sin comps de subasta específicos.', ARRAY['Wine-Searcher (promedio EE.UU.)', 'Total Wine & More', 'Taninowines'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/clos+mogadur+vi+de+finca+doca+priorat+catalonia+spain'),
  ('Finca Dofí', 'Álvaro Palacios', 'priorat'::wine_region, 'Gratallops', 'tinto'::wine_color, 2022, ARRAY['Garnacha', 'Cariñena'], 125, 90, 140, 'medio'::confidence_level, 'Segundo vino histórico de Álvaro Palacios (primera finca adquirida); precio consistente entre varios retailers de EE.UU. y Europa, sin evidencia de reventa documentada.', ARRAY['Wine-Searcher (promedio EE.UU.)', 'Binny''s Beverage Depot', 'Decántalo'], '2026-07-27'::date, 'https://www.wine-searcher.com/find/alvaro+palacio+finca+dofi+doca+priorat+catalonia+spain'),
  ('Les Terrasses', 'Álvaro Palacios', 'priorat'::wine_region, 'Gratallops', 'tinto'::wine_color, 2023, ARRAY['Garnacha', 'Cariñena', 'Syrah'], 32, 24, 45, 'medio'::confidence_level, 'Vino de entrada de Álvaro Palacios y el más vendido en volumen de la bodega; precio variable entre mercado español y estadounidense, sin mercado secundario propio.', ARRAY['Vino-Vi', 'K&L Wines', 'Plum Market'], '2026-07-27'::date, 'https://www.vino-vi.com/es/vino-tinto/3286-les-terrasses-2023.html'),
  ('Embruix de Vall Llach', 'Celler Vall Llach', 'priorat'::wine_region, 'Porrera', 'tinto'::wine_color, 2021, ARRAY['Merlot', 'Garnacha', 'Cariñena'], 21, 18, 24, 'medio'::confidence_level, 'Vino de entrada de una bodega histórica del Priorat (fundada por Lluís Llach); precio consistente en Bodeboca, sin evidencia de mercado secundario.', ARRAY['Bodeboca', 'Vinumpriorat.com'], '2026-07-27'::date, 'https://www.bodeboca.com/vino/embruix-vall-llach-2021'),
  ('Doix', 'Celler Mas Doix', 'priorat'::wine_region, 'Poboleda', 'tinto'::wine_color, 2021, ARRAY['Garnacha', 'Cariñena'], 100, 90, 110, 'medio'::confidence_level, 'Vino de gama alta de bodega familiar de Poboleda con viñas viejas; precio de Wine Palace (€93,65-102) es la referencia principal, sin comps de mercado secundario.', ARRAY['Wine Palace', 'Vino-Vi', 'Bodeboca'], '2026-07-27'::date, 'https://www.vino-vi.com/es/vino-tinto/2676-doix-2021.html');
